# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: local-bos .NET API

on:
  pull_request:
    types: [] # Defaults to opened, reopened and synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore API dependencies
      run: (cd api && dotnet restore)
    - name: API Build
      run: (cd api && dotnet build --no-restore)
    - name: API Formatting Checks
      run: (cd api && dotnet format --no-restore --verify-no-changes)
    - name: API Tests
      run: (cd api/Api.Tests && dotnet test --no-build --verbosity normal)
